services:
    forumhulp.loginwithemail.listener:
        class: forumhulp\loginwithemail\event\listener
        arguments:
            - @user
            - @config
            - @request
            - @template
        tags:
            - { name: event.listener }
    forumhulp.loginwithemail.controller:
        class: forumhulp\loginwithemail\controller\controller
        arguments:
            - @dbal.conn
            - @template
            - @user
            - @request
