services:
    forumhulp.loginwithemail.listener:
        class: forumhulp\loginwithemail\event\listener
        arguments:
            - '@user'
            - '@dbal.conn'
            - '@configv
            - '@request'
            - '@template'
        tags:
            - { name: event.listener }
    forumhulp.loginwithemail.controller:
        class: forumhulp\loginwithemail\controller\controller
        arguments:
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '@request'
